close all;
clear
autoRetrainWithThreholdANFIS;
predicted1 = predictedV;
autoRetrainWithThreholdNARX;
LRMNewJob;
predictedV3 = predictedV;
figure(1)
plot(predicted1);
hold on;
plot(actualV);
hold off
legend('Predicted values generated by ANFIS','Actual values')
xlabel('Time with 1-Hour unit')
ylabel('Mean of memory consumption')
figure(2)
predictedV2 = cell2mat(ys(1:end));
plot(predictedV2);
hold on
plot(actualV); 
legend('Predicted values generated by NAR','Actual values')
hold off
xlabel('Time with 1-Hour unit')
ylabel('Mean of memory consumption')
figure(3)
plot(predictedV3);
hold on
plot(actualV); 
legend('Predicted values generated by LR','Actual values')
hold off
xlabel('Time with 1-Hour unit')
ylabel('Mean of memory consumption')
